input_stream: "input_video"
input_side_packet: "output_file"
output_stream: "output_video"


node {
  calculator: "PoseTrackingGpuSubgraph"
  input_stream: "input_video"
  output_stream: "output_video"
  output_stream: "pose_landmarks"
}

node {
  calculator: "PoseLandmarksToCSVCalculator"
  input_side_packet: "CSV_OUTPUT_FILE_PATH:output_file"
  input_stream: "NORM_LANDMARKS:pose_landmarks"
}