input_stream: "input_video"
input_side_packet: "output_file"
output_stream: "output_video"

node {
  calculator: "DetectionsGPUSubgraph"
  input_stream: "input_video"
  output_stream: "DETECTIONS:output_detections"
  output_stream: "LANDMARKS:multi_hand_landmarks"
  output_stream: "output_video"
}

node {
  calculator: "DetectionsToCSVCalculator"
  input_side_packet: "CSV_OUTPUT_FILE_PATH: output_file"
  input_stream: "DETECTIONS:output_detections"
  input_stream: "NORM_LANDMARKS:multi_hand_landmarks"
}