input_stream: "input_video"
input_side_packet: "output_file"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:multi_hand_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}


node {
  calculator: "DetectionsGPUSubgraph"
  input_stream: "throttled_input_video"
  output_stream: "output_detections"
  output_stream: "multi_hand_landmarks"
  output_stream: "detection_render_data"
  output_stream: "multi_hand_rects_render_data"
  output_stream: "multi_palm_rects_render_data"
  output_stream: "render_data"
  output_stream: "multi_hand_landmarks_render_data"
}

node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "detection_render_data"
  input_stream: "multi_hand_rects_render_data"
  input_stream: "multi_palm_rects_render_data"
  input_stream: "render_data"
  input_stream: "VECTOR:0:multi_hand_landmarks_render_data"
  output_stream: "IMAGE_GPU:output_video"
}

node {
  calculator: "DetectionsToCSVCalculator"
  input_side_packet: "CSV_OUTPUT_FILE_PATH:output_file"
  input_stream: "DETECTIONS:output_detections"
  input_stream: "NORM_LANDMARKS:multi_hand_landmarks"
}