
cc_library(
    name = "detections_to_csv_calculator",
    srcs = ["detections_to_csv_calculator.cc"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@mediapipe//mediapipe/framework:calculator_framework",
        "@mediapipe//mediapipe/framework/port:ret_check",
        "@mediapipe//mediapipe/framework/port:status",
        # "@com_google_absl//absl/strings",
    ],
    alwayslink = 1,
)